distance:
  # The default world you are teleported to when using /rtp.
  # (only supported when use-original is set to true)
  # (playerworld: the world you're is currently in)
  # [default: playerworld]
  default_world: playerworld
  # Maximum distance you want you to be teleported.
  # (0 = world border size / 2)
  # (otherwise, must be more than 0)
  # [default: auto]
  # Range: > 0
  max_distance: 0
  # Minimum distance you want you to be teleported.
  # (must be more than 0)
  # [default: 1]
  min_distance: 1

inter-dimensions-command:
  # Do you want to enable the /rtpd command?
  # This commands allows you to teleport to a random location in a specified dimension.
  # [default: true]
  inter-dim: true
  # Do you want to whitelist or blacklist destination dimensions?
  # [default: false]
  use-whitelist: false
  # The dimension whitelist / blacklist.
  # (works with namespaces:paths only)
  # [default: minecraft:the_end (The End - vanilla) and twilight:dimension (The Twilight Forest - mod]
  whitelist-dimension:
    - 'minecraft:the_end'
    - 'twilight:dimension'

inter-biomes-command:
  # Do you want to enable the /rtpb command?
  # This commands allows you to teleport to a random location in a specified biome.
  # [default: true]
  inter-biome: true

others:
  # How many times should the mod look for a safe teleport destination?
  # (only supported when use-original is set to true)
  # [-1: infinite, default: -1]
  max-tries: -1
  # What RTP system should the mod use?
  # true = the mod's custom RTP system
  # false = the vanilla /spreadplayers system
  # [default: true]
  use-original: true
  # Do you want to whitelist or blacklist destination biomes?
  # true = whitelist
  # false = blacklist
  # [default: false]
  use-biome-whitelist: false
  # The biome whitelist / blacklist.
  # (uses namespace:path format)
  # [default: all vanilla oceans]
  biome-whitelist:
    - 'minecraft:warm_ocean'
    - 'minecraft:lukewarm_ocean'
    - 'minecraft:deep_lukewarm_ocean'
    - 'minecraft:ocean'
    - 'minecraft:deep_ocean'
    - 'minecraft:cold_ocean'
    - 'minecraft:deep_cold_ocean'
    - 'minecraft:frozen_ocean'
    - 'minecraft:deep_frozen_ocean'

  # How long do you want the command cooldown to be?
  # (range: 0 ~ 1000)
  # [default: 0]
  cooldown: 0
